services:
  app:
    build: .
    container_name: my_app
    ports:
      - "3001:3001"
    networks:
      - app_network
    environment:
      - PGUSER=admin
      - PGHOST=postgres
      - PGDATABASE=my_app_db
      - PGPASSWORD=admin
      - PGPORT=5432
      # - NODE_ENV=development # Важно для dev-зависимостей
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      # Добавляем volume для node_modules, чтобы избежать проблем
      - /app/node_modules
    depends_on:
      - postgres
    # Для разработки используем эту команду
    command: sh -c "npm install && npm run dev"
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
  microservices-network:
    driver: bridge
