version: "3.8"

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - PGUSER=admin
      - PGHOST=postgres
      - PGDATABASE=my_app_db
      - PGPASSWORD=admin
      - PGPORT=5432
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
